In [1]:
import numpy as np
# import pandas as pd

a = np.matrix([1, 2, 3, 4])
b = np.matrix([4, 1, 9, -1])

list2 = ([[1, 2, 3, 4], 
               [1, 2, 1, 1]])

A = np.matrix([[3, -1], [-4, 0]])
B = np.matrix([[0, 2], [3, 2]])

print(A)
print(B)

[[ 3 -1]
 [-4  0]]
[[0 2]
 [3 2]]


In [2]:
import numpy as np
R = np.matrix([[243, 243, 243], [243, 183, 243], [243, 243, 243]])
G = np.matrix([[98, 98, 98], [98, 117, 98], [98, 98, 98]])
B = np.matrix([[166, 166, 166], [166, 255, 166], [166, 166, 166]])

print(1/3*(R + G + B))

[[169. 169. 169.]
 [169. 185. 169.]
 [169. 169. 169.]]


In [3]:
import numpy as np
A = np.matrix([[1, 2], [0, 1]])
B= np.matrix([[1, 2], [3, 4]])

C = np.matrix([[3, 2], [4, 5]])
D= np.matrix([[-2], [1]])
print(A*B)
print(B*A)

print(C*D)
print(D*C)

[[ 7 10]
 [ 3  4]]
[[ 1  4]
 [ 3 10]]
[[-4]
 [-3]]


ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [4]:
import numpy as np
A = np.matrix([[1, 2], [0, 1]])
B= np.matrix([[1, 2], [3, 4]])

C = np.matrix([[3, 2], [4, 5]])
D= np.matrix([[-2], [1]])

I = np.matrix([[1, 0], [0, 1]]) # 항등행렬
print(A)
print(A*I)
print(I*A)

# print(A*B)
# print(B*A)

# print(C*D)
# print(D*C)

[[1 2]
 [0 1]]
[[1 2]
 [0 1]]
[[1 2]
 [0 1]]


In [5]:
T = np.matrix([[0, 1, 1], [0, 0, 1], [0, 0, 0]])
A = np.matrix([[0, 0, 0], [0, 255, 0], [0, 0, 0]])

print(A*T) # 오른쪽
print(T*A) # 위쪽

[[  0   0   0]
 [  0   0 255]
 [  0   0   0]]
[[  0 255   0]
 [  0   0   0]
 [  0   0   0]]
